// Auto-generated by fetch-artist.js — do not edit manually
// Usage: node fetch-artist.js "Artist Name"
window.DISCOGRAPHY = {
  "radiohead": {
    "name": "Radiohead",
    "mbid": "a74b1b7f-71a5-4011-9441-d0b5e4122711",
    "bio": "Group from Abingdon-on-Thames. Formed 1991.",
    "accent": "#d97842",
    "albums": [
      {
        "id": "radiohead-pablo-honey",
        "mbid": "cd76f76b-ff15-3784-a71d-4da3078a6851",
        "title": "Pablo Honey",
        "year": 1993,
        "cover": "covers/radiohead-pablo-honey.jpg",
        "palette": [
          "#1a3a5c",
          "#7ba7c9",
          "#e8d5b7"
        ],
        "motif": "wave",
        "tracks": [
          [
            "You",
            209
          ],
          [
            "Creep",
            236
          ],
          [
            "How Do You?",
            132
          ],
          [
            "Stop Whispering",
            326
          ],
          [
            "Thinking About You",
            162
          ],
          [
            "Anyone Can Play Guitar",
            218
          ],
          [
            "Ripcord",
            190
          ],
          [
            "Vegetable",
            193
          ],
          [
            "Prove Yourself",
            145
          ],
          [
            "I Can’t",
            253
          ],
          [
            "Lurgee",
            188
          ],
          [
            "Blow Out",
            280
          ]
        ]
      },
      {
        "id": "radiohead-bends",
        "mbid": "b8048f24-c026-3398-b23a-b5e50716cbc7",
        "title": "The Bends",
        "year": 1994,
        "cover": "covers/radiohead-bends.jpg",
        "palette": [
          "#2a2a2a",
          "#c8c8c8",
          "#d4a574"
        ],
        "motif": "grid",
        "tracks": [
          [
            "Planet Telex",
            259
          ],
          [
            "The Bends",
            246
          ],
          [
            "High and Dry",
            258
          ],
          [
            "Fake Plastic Trees",
            291
          ],
          [
            "Bones",
            189
          ],
          [
            "(Nice Dream)",
            233
          ],
          [
            "Just",
            234
          ],
          [
            "My Iron Lung",
            276
          ],
          [
            "Bullet Proof..I Wish I Was",
            209
          ],
          [
            "Black Star",
            247
          ],
          [
            "Sulk",
            223
          ],
          [
            "Street Spirit (Fade Out)",
            252
          ]
        ]
      },
      {
        "id": "radiohead-ok-computer",
        "mbid": "b1392450-e666-3926-a536-22c65f834433",
        "title": "OK Computer",
        "year": 1997,
        "cover": "covers/radiohead-ok-computer.jpg",
        "palette": [
          "#b8332a",
          "#1a1a1a",
          "#e8b89d"
        ],
        "motif": "weep",
        "tracks": [
          [
            "Airbag",
            284
          ],
          [
            "Paranoid Android",
            383
          ],
          [
            "Subterranean Homesick Alien",
            268
          ],
          [
            "Exit Music (for a Film)",
            265
          ],
          [
            "Let Down",
            299
          ],
          [
            "Karma Police",
            262
          ],
          [
            "Fitter Happier",
            117
          ],
          [
            "Electioneering",
            231
          ],
          [
            "Climbing Up the Walls",
            285
          ],
          [
            "No Surprises",
            229
          ],
          [
            "Lucky",
            260
          ],
          [
            "The Tourist",
            325
          ]
        ]
      },
      {
        "id": "radiohead-kid-a",
        "mbid": "e75c0549-ad55-39e3-8025-c72c5d4a3c5d",
        "title": "Kid A",
        "year": 2000,
        "cover": "covers/radiohead-kid-a.jpg",
        "palette": [
          "#1a0f3a",
          "#e8a020",
          "#c0386b"
        ],
        "motif": "splash",
        "tracks": [
          [
            "Everything in Its Right Place",
            251
          ],
          [
            "Kid A",
            285
          ],
          [
            "The National Anthem",
            352
          ],
          [
            "How to Disappear Completely",
            356
          ],
          [
            "Treefingers",
            223
          ],
          [
            "Optimistic",
            316
          ],
          [
            "In Limbo",
            211
          ],
          [
            "Idioteque",
            309
          ],
          [
            "Morning Bell",
            276
          ],
          [
            "Motion Picture Soundtrack",
            419
          ]
        ]
      },
      {
        "id": "radiohead-amnesiac",
        "mbid": "bca9280e-28b4-327f-8fe0-fd918579e486",
        "title": "Amnesiac",
        "year": 2001,
        "cover": "covers/radiohead-amnesiac.jpg",
        "palette": [
          "#2d4a3e",
          "#e8e0c8",
          "#a8956b"
        ],
        "motif": "leaves",
        "tracks": [
          [
            "Packt Like Sardines in a Crushd Tin Box",
            240
          ],
          [
            "Pyramid Song",
            289
          ],
          [
            "Pulk/Pull Revolving Doors",
            247
          ],
          [
            "You and Whose Army?",
            191
          ],
          [
            "I Might Be Wrong",
            294
          ],
          [
            "Knives Out",
            255
          ],
          [
            "Morning Bell/Amnesiac",
            194
          ],
          [
            "Dollars and Cents",
            292
          ],
          [
            "Hunting Bears",
            121
          ],
          [
            "Like Spinning Plates",
            237
          ],
          [
            "Life in a Glasshouse",
            275
          ]
        ]
      },
      {
        "id": "radiohead-hail-to-the-thief",
        "mbid": "5c14fd50-a2f1-3672-9537-b0dad91bea2f",
        "title": "Hail to the Thief",
        "year": 2003,
        "cover": "covers/radiohead-hail-to-the-thief.jpg",
        "palette": [
          "#5c3a1f",
          "#d4a574",
          "#8c5a2e"
        ],
        "motif": "soul",
        "tracks": [
          [
            "2 + 2 = 5 (The Lukewarm.)",
            199
          ],
          [
            "Sit Down. Stand Up. (Snakes & Ladders.)",
            260
          ],
          [
            "Sail to the Moon. (Brush the Cobwebs Out of the Sky.)",
            258
          ],
          [
            "Backdrifts. (Honeymoon Is Over.)",
            323
          ],
          [
            "Go to Sleep. (Little Man Being Erased.)",
            202
          ],
          [
            "Where I End and You Begin. (The Sky Is Falling In.)",
            269
          ],
          [
            "We Suck Young Blood. (Your Time Is Up.)",
            297
          ],
          [
            "The Gloaming. (Softly Open Our Mouths in the Cold.)",
            212
          ],
          [
            "There There. (The Boney King of Nowhere.)",
            324
          ],
          [
            "I Will. (No Man’s Land.)",
            119
          ],
          [
            "A Punchup at a Wedding. (No No No No No No No No.)",
            297
          ],
          [
            "Myxomatosis. (Judge, Jury & Executioner.)",
            233
          ],
          [
            "Scatterbrain. (As Dead as Leaves.)",
            202
          ],
          [
            "A Wolf at the Door. (It Girl. Rag Doll.)",
            201
          ]
        ]
      },
      {
        "id": "radiohead-in-rainbows",
        "mbid": "6e335887-60ba-38f0-95af-fae7774336bf",
        "title": "In Rainbows",
        "year": 2007,
        "cover": "covers/radiohead-in-rainbows.jpg",
        "palette": [
          "#1f1f1f",
          "#e8e8e8",
          "#b85c2e"
        ],
        "motif": "collage",
        "tracks": [
          [
            "15 Step",
            237
          ],
          [
            "Bodysnatchers",
            242
          ],
          [
            "Nude",
            255
          ],
          [
            "Weird Fishes/Arpeggi",
            318
          ],
          [
            "All I Need",
            229
          ],
          [
            "Faust Arp",
            130
          ],
          [
            "Reckoner",
            290
          ],
          [
            "House of Cards",
            328
          ],
          [
            "Jigsaw Falling Into Place",
            249
          ],
          [
            "Videotape",
            280
          ]
        ]
      },
      {
        "id": "radiohead-king-of-limbs",
        "mbid": "899b6d09-807e-4c18-a6d4-3642e00d6a3d",
        "title": "The King of Limbs",
        "year": 2011,
        "cover": "covers/radiohead-king-of-limbs.jpg",
        "palette": [
          "#c0392b",
          "#f4d03f",
          "#2874a6"
        ],
        "motif": "band",
        "tracks": [
          [
            "Bloom",
            315
          ],
          [
            "Morning Mr Magpie",
            281
          ],
          [
            "Little by Little",
            267
          ],
          [
            "Feral",
            193
          ],
          [
            "Lotus Flower",
            301
          ],
          [
            "Codex",
            287
          ],
          [
            "Give Up the Ghost",
            290
          ],
          [
            "Separator",
            320
          ]
        ]
      },
      {
        "id": "radiohead-a-moon-shaped-pool",
        "mbid": "bbce0087-d386-4246-a51d-dbcdfdbe8fb2",
        "title": "A Moon Shaped Pool",
        "year": 2016,
        "cover": "covers/radiohead-a-moon-shaped-pool.jpg",
        "palette": [
          "#f5f5f0",
          "#bdb8a8",
          "#2a2a2a"
        ],
        "motif": "blank",
        "tracks": [
          [
            "Burn the Witch",
            220
          ],
          [
            "Daydreaming",
            384
          ],
          [
            "Decks Dark",
            281
          ],
          [
            "Desert Island Disk",
            224
          ],
          [
            "Ful Stop",
            367
          ],
          [
            "Glass Eyes",
            172
          ],
          [
            "Identikit",
            266
          ],
          [
            "The Numbers",
            345
          ],
          [
            "Present Tense",
            306
          ],
          [
            "Tinker Tailor Soldier Sailor Rich Man Poor Man Beggar Man Thief",
            303
          ],
          [
            "True Love Waits",
            283
          ]
        ]
      }
    ]
  },
  "beatles": {
    "name": "The Beatles",
    "mbid": "b10bbbfc-cf9e-42e0-be17-e2c3e1d2600d",
    "bio": "Group from Liverpool. 1960–1970.",
    "accent": "#c97a1f",
    "albums": [
      {
        "id": "beatles-please-please-me",
        "mbid": "de208292-8db5-3aed-a14a-b37a84d8c521",
        "title": "Please Please Me",
        "year": 1963,
        "cover": "covers/beatles-please-please-me.jpg",
        "palette": [
          "#1a3a5c",
          "#7ba7c9",
          "#e8d5b7"
        ],
        "motif": "wave",
        "tracks": [
          [
            "I Saw Her Standing There",
            176
          ],
          [
            "Misery",
            110
          ],
          [
            "Anna (Go to Him)",
            178
          ],
          [
            "Chains",
            146
          ],
          [
            "Boys",
            148
          ],
          [
            "Ask Me Why",
            148
          ],
          [
            "Please Please Me",
            122
          ],
          [
            "Love Me Do",
            142
          ],
          [
            "P.S. I Love You",
            124
          ],
          [
            "Baby It’s You",
            158
          ],
          [
            "Do You Want to Know a Secret",
            120
          ],
          [
            "A Taste of Honey",
            125
          ],
          [
            "There’s a Place",
            113
          ],
          [
            "Twist and Shout",
            153
          ]
        ]
      },
      {
        "id": "beatles-with-the-beatles",
        "mbid": "a63dc65f-09f2-359b-a10e-648f00ecd96c",
        "title": "With The Beatles",
        "year": 1963,
        "cover": "covers/beatles-with-the-beatles.jpg",
        "palette": [
          "#2a2a2a",
          "#c8c8c8",
          "#d4a574"
        ],
        "motif": "grid",
        "tracks": [
          [
            "I Want to Hold Your Hand",
            147
          ],
          [
            "It Won't Be Long",
            133
          ],
          [
            "All I've Got to Do",
            124
          ],
          [
            "Little Child",
            108
          ],
          [
            "Don't Bother Me",
            149
          ],
          [
            "Please Mister Postman",
            157
          ],
          [
            "She Loves You",
            141
          ],
          [
            "Roll Over Beethoven",
            167
          ],
          [
            "You Really Got a Hold on Me",
            183
          ],
          [
            "I Wanna Be Your Man",
            119
          ],
          [
            "Devil In Her Heart",
            147
          ],
          [
            "I Saw Her Standing There",
            175
          ]
        ]
      },
      {
        "id": "beatles-introducing-the-beatles",
        "mbid": "653895d1-b592-3758-8bb1-8b9ba2bd6cb0",
        "title": "Introducing… The Beatles",
        "year": 1964,
        "cover": "covers/beatles-introducing-the-beatles.jpg",
        "palette": [
          "#8a2c1f",
          "#f0e8d8",
          "#c4b89d"
        ],
        "motif": "mountain",
        "tracks": [
          [
            "I Saw Her Standing There",
            176
          ],
          [
            "Misery",
            105
          ],
          [
            "Anna",
            178
          ],
          [
            "Chains",
            146
          ],
          [
            "Boys",
            148
          ],
          [
            "Ask Me Why",
            148
          ],
          [
            "Please Please Me",
            122
          ],
          [
            "Baby It’s You",
            158
          ],
          [
            "Do You Want to Know a Secret?",
            120
          ],
          [
            "A Taste of Honey",
            125
          ],
          [
            "There’s a Place",
            113
          ],
          [
            "Twist and Shout",
            153
          ]
        ]
      },
      {
        "id": "beatles-meet-the-beatles",
        "mbid": "c2c696fc-6beb-3dfb-bb15-7bb021ebeb5d",
        "title": "Meet The Beatles!",
        "year": 1964,
        "cover": "covers/beatles-meet-the-beatles.jpg",
        "palette": [
          "#b8332a",
          "#1a1a1a",
          "#e8b89d"
        ],
        "motif": "weep",
        "tracks": [
          [
            "I Want to Hold Your Hand",
            149
          ],
          [
            "I Saw Her Standing There",
            177
          ],
          [
            "This Boy",
            138
          ],
          [
            "It Won’t Be Long",
            136
          ],
          [
            "All I’ve Got to Do",
            128
          ],
          [
            "All My Loving",
            130
          ],
          [
            "Don’t Bother Me",
            151
          ],
          [
            "Little Child",
            110
          ],
          [
            "Till There Was You",
            140
          ],
          [
            "Hold Me Tight",
            154
          ],
          [
            "I Wanna Be Your Man",
            122
          ],
          [
            "Not a Second Time",
            127
          ]
        ]
      },
      {
        "id": "beatles-twist-and-shout",
        "mbid": "31770e0a-e537-376d-a7c0-48e507f3105e",
        "title": "Twist and Shout",
        "year": 1964,
        "cover": "covers/beatles-twist-and-shout.jpg",
        "palette": [
          "#1a0f3a",
          "#e8a020",
          "#c0386b"
        ],
        "motif": "splash",
        "tracks": [
          [
            "Anna (Go to Him)",
            175
          ],
          [
            "Chains",
            142
          ],
          [
            "Boys",
            145
          ],
          [
            "Ask Me Why",
            142
          ],
          [
            "Please Please Me",
            120
          ],
          [
            "Love Me Do",
            142
          ],
          [
            "From Me to You",
            120
          ],
          [
            "P.S. I Love You",
            122
          ],
          [
            "Baby It’s You",
            153
          ],
          [
            "Do You Want to Know a Secret",
            115
          ],
          [
            "A Taste of Honey",
            121
          ],
          [
            "There’s a Place",
            110
          ],
          [
            "Twist and Shout",
            152
          ],
          [
            "She Loves You",
            143
          ]
        ]
      },
      {
        "id": "beatles-beatles-second-album",
        "mbid": "387bc6cc-ac60-365f-819b-fbc78c486065",
        "title": "The Beatles’ Second Album",
        "year": 1964,
        "cover": "covers/beatles-beatles-second-album.jpg",
        "palette": [
          "#2d4a3e",
          "#e8e0c8",
          "#a8956b"
        ],
        "motif": "leaves",
        "tracks": [
          [
            "Roll Over Beethoven",
            164
          ],
          [
            "Thank You Girl",
            121
          ],
          [
            "You Really Got a Hold on Me",
            178
          ],
          [
            "Devil in Her Heart",
            143
          ],
          [
            "Money (That’s What I Want)",
            167
          ],
          [
            "You Can’t Do That",
            153
          ],
          [
            "Long Tall Sally",
            123
          ],
          [
            "I Call Your Name",
            129
          ],
          [
            "Please Mister Postman",
            154
          ],
          [
            "I’ll Get You",
            124
          ],
          [
            "She Loves You",
            139
          ]
        ]
      },
      {
        "id": "beatles-beatles-long-tall-sally",
        "mbid": "d0c93a59-fc4d-3d76-ac38-9c1d11071802",
        "title": "The Beatles’ Long Tall Sally",
        "year": 1964,
        "cover": "covers/beatles-beatles-long-tall-sally.jpg",
        "palette": [
          "#5c3a1f",
          "#d4a574",
          "#8c5a2e"
        ],
        "motif": "soul",
        "tracks": [
          [
            "I Want to Hold Your Hand",
            151
          ],
          [
            "I Saw Her Standing There",
            178
          ],
          [
            "You Really Got a Hold on Me",
            185
          ],
          [
            "Devil in Her Heart",
            151
          ],
          [
            "Roll Over Beethoven",
            169
          ],
          [
            "Misery",
            112
          ],
          [
            "Long Tall Sally",
            127
          ],
          [
            "I Call Your Name",
            134
          ],
          [
            "Please Mister Postman",
            159
          ],
          [
            "This Boy",
            138
          ],
          [
            "I’ll Get You",
            128
          ],
          [
            "You Can’t Do That",
            153
          ]
        ]
      },
      {
        "id": "beatles-something-new",
        "mbid": "451e7aa4-a782-3979-9aa0-98c03a246fe9",
        "title": "Something New",
        "year": 1964,
        "cover": "covers/beatles-something-new.jpg",
        "palette": [
          "#1f1f1f",
          "#e8e8e8",
          "#b85c2e"
        ],
        "motif": "collage",
        "tracks": [
          [
            "I’ll Cry Instead",
            124
          ],
          [
            "Things We Said Today",
            155
          ],
          [
            "Any Time at All",
            130
          ],
          [
            "When I Get Home",
            134
          ],
          [
            "Slow Down",
            174
          ],
          [
            "Matchbox",
            97
          ],
          [
            "Tell Me Why",
            126
          ],
          [
            "And I Love Her",
            148
          ],
          [
            "I’m Happy Just to Dance With You",
            116
          ],
          [
            "If I Fell",
            139
          ],
          [
            "Komm, gib mir deine Hand (I Want to Hold Your Hand)",
            144
          ]
        ]
      },
      {
        "id": "beatles-beatles-for-sale",
        "mbid": "f50a3b6f-27f0-3832-bd3f-3568dc557d95",
        "title": "Beatles for Sale",
        "year": 1964,
        "cover": "covers/beatles-beatles-for-sale.jpg",
        "palette": [
          "#c0392b",
          "#f4d03f",
          "#2874a6"
        ],
        "motif": "band",
        "tracks": [
          [
            "No Reply",
            138
          ],
          [
            "I’m a Loser",
            154
          ],
          [
            "Baby’s in Black",
            128
          ],
          [
            "Rock and Roll Music",
            154
          ],
          [
            "I’ll Follow the Sun",
            111
          ],
          [
            "Mr. Moonlight",
            157
          ],
          [
            "Kansas City",
            153
          ],
          [
            "Eight Days a Week",
            165
          ],
          [
            "Words of Love",
            135
          ],
          [
            "Honey Don’t",
            180
          ],
          [
            "Every Little Thing",
            125
          ],
          [
            "I Don’t Want to Spoil the Party",
            156
          ],
          [
            "What You’re Doing",
            155
          ],
          [
            "Everybody’s Trying to Be My Baby",
            144
          ]
        ]
      },
      {
        "id": "beatles-beatles-65",
        "mbid": "2d111aea-50f8-33cc-ab63-780bc57068c0",
        "title": "Beatles ’65",
        "year": 1964,
        "cover": "covers/beatles-beatles-65.jpg",
        "palette": [
          "#f5f5f0",
          "#bdb8a8",
          "#2a2a2a"
        ],
        "motif": "blank",
        "tracks": [
          [
            "No Reply",
            135
          ],
          [
            "I’m a Loser",
            151
          ],
          [
            "Baby’s in Black",
            122
          ],
          [
            "Rock and Roll Music",
            122
          ],
          [
            "I’ll Follow the Sun",
            106
          ],
          [
            "Mr. Moonlight",
            155
          ],
          [
            "Honey Don’t",
            176
          ],
          [
            "I’ll Be Back",
            142
          ],
          [
            "She’s a Woman",
            177
          ],
          [
            "I Feel Fine",
            140
          ],
          [
            "Everybody’s Trying to Be My Baby",
            144
          ]
        ]
      },
      {
        "id": "beatles-beatles-vi",
        "mbid": "3d402374-9538-3c09-8566-2850fa3fce3f",
        "title": "Beatles VI",
        "year": 1965,
        "cover": "covers/beatles-beatles-vi.jpg",
        "palette": [
          "#2d5016",
          "#a8c45e",
          "#1a1a1a"
        ],
        "motif": "crossing",
        "tracks": [
          [
            "Kansas City",
            150
          ],
          [
            "Eight Days a Week",
            163
          ],
          [
            "You Like Me Too Much",
            154
          ],
          [
            "Bad Boy",
            137
          ],
          [
            "I Don’t Want to Spoil the Party",
            153
          ],
          [
            "Words of Love",
            130
          ],
          [
            "What You’re Doing",
            150
          ],
          [
            "Yes It Is",
            160
          ],
          [
            "Dizzy Miss Lizzie",
            171
          ],
          [
            "Tell Me What You See",
            155
          ],
          [
            "Every Little Thing",
            121
          ]
        ]
      },
      {
        "id": "beatles-help",
        "mbid": "0d44e1cb-c6e0-3453-8b68-4d2082f05421",
        "title": "Help!",
        "year": 1965,
        "cover": "covers/beatles-help.jpg",
        "palette": [
          "#1a1a1a",
          "#d4af37",
          "#8c7a3a"
        ],
        "motif": "windows",
        "tracks": [
          [
            "Help!",
            155
          ],
          [
            "The Night Before",
            153
          ],
          [
            "From Me to You Fantasy",
            123
          ],
          [
            "You've Got to Hide Your Love Away",
            128
          ],
          [
            "I Need You",
            148
          ],
          [
            "In the Tyrol",
            141
          ],
          [
            "Another Girl",
            122
          ],
          [
            "Another Hard Day's Night",
            148
          ],
          [
            "Ticket to Ride",
            183
          ],
          [
            "The Bitter End / You Can't Do That",
            140
          ],
          [
            "You're Gonna Lose That Girl",
            138
          ],
          [
            "The Chase",
            144
          ]
        ]
      },
      {
        "id": "beatles-rubber-soul",
        "mbid": "dca03435-8adb-30a5-ba82-5a162267ff38",
        "title": "Rubber Soul",
        "year": 1965,
        "cover": "covers/beatles-rubber-soul.jpg",
        "palette": [
          "#1a3a5c",
          "#7ba7c9",
          "#e8d5b7"
        ],
        "motif": "wave",
        "tracks": [
          [
            "I’ve Just Seen a Face",
            129
          ],
          [
            "Norwegian Wood (This Bird Has Flown)",
            128
          ],
          [
            "You Won’t See Me",
            208
          ],
          [
            "Think for Yourself",
            142
          ],
          [
            "The Word",
            168
          ],
          [
            "Michelle",
            167
          ],
          [
            "It’s Only Love",
            119
          ],
          [
            "Girl",
            154
          ],
          [
            "I’m Looking Through You",
            153
          ],
          [
            "In My Life",
            150
          ],
          [
            "Wait",
            138
          ],
          [
            "Run for Your Life",
            143
          ]
        ]
      },
      {
        "id": "beatles-yesterday-and-today",
        "mbid": "0a4d1024-3463-3c74-8500-ea011bd5d523",
        "title": "Yesterday and Today",
        "year": 1966,
        "cover": "covers/beatles-yesterday-and-today.jpg",
        "palette": [
          "#2a2a2a",
          "#c8c8c8",
          "#d4a574"
        ],
        "motif": "grid",
        "tracks": [
          [
            "Drive My Car",
            145
          ],
          [
            "I’m Only Sleeping",
            178
          ],
          [
            "Nowhere Man",
            160
          ],
          [
            "Dr. Robert",
            134
          ],
          [
            "Yesterday",
            124
          ],
          [
            "Act Naturally",
            147
          ],
          [
            "And Your Bird Can Sing",
            122
          ],
          [
            "If I Needed Someone",
            139
          ],
          [
            "We Can Work It Out",
            130
          ],
          [
            "What Goes On",
            164
          ],
          [
            "Day Tripper",
            167
          ]
        ]
      },
      {
        "id": "beatles-revolver",
        "mbid": "72d15666-99a7-321e-b1f3-a3f8c09dff9f",
        "title": "Revolver",
        "year": 1966,
        "cover": "covers/beatles-revolver.jpg",
        "palette": [
          "#8a2c1f",
          "#f0e8d8",
          "#c4b89d"
        ],
        "motif": "mountain",
        "tracks": [
          [
            "Taxman",
            156
          ],
          [
            "Eleanor Rigby",
            131
          ],
          [
            "Love You To",
            180
          ],
          [
            "Here, There and Everywhere",
            149
          ],
          [
            "Yellow Submarine",
            160
          ],
          [
            "She Said She Said",
            159
          ],
          [
            "Good Day Sunshine",
            128
          ],
          [
            "For No One",
            123
          ],
          [
            "I Want to Tell You",
            150
          ],
          [
            "Got to Get You Into My Life",
            151
          ],
          [
            "Tomorrow Never Knows",
            180
          ]
        ]
      },
      {
        "id": "beatles-sgt-pepper-s-lonely-hearts-club-band",
        "mbid": "9f7a4c28-8fa2-3113-929c-c47a9f7982c3",
        "title": "Sgt. Pepper’s Lonely Hearts Club Band",
        "year": 1967,
        "cover": "covers/beatles-sgt-pepper-s-lonely-hearts-club-band.jpg",
        "palette": [
          "#b8332a",
          "#1a1a1a",
          "#e8b89d"
        ],
        "motif": "weep",
        "tracks": [
          [
            "Sgt. Pepper’s Lonely Hearts Club Band",
            122
          ],
          [
            "With a Little Help From My Friends",
            164
          ],
          [
            "Lucy in the Sky With Diamonds",
            210
          ],
          [
            "Getting Better",
            170
          ],
          [
            "Fixing a Hole",
            159
          ],
          [
            "She’s Leaving Home",
            217
          ],
          [
            "Being for the Benefit of Mr. Kite!",
            159
          ],
          [
            "Within You Without You",
            307
          ],
          [
            "When I’m Sixty‐Four",
            160
          ],
          [
            "Lovely Rita",
            164
          ],
          [
            "Good Morning Good Morning",
            163
          ],
          [
            "Sgt. Pepper’s Lonely Hearts Club Band (reprise)",
            79
          ],
          [
            "A Day in the Life",
            334
          ]
        ]
      },
      {
        "id": "beatles-beatles",
        "mbid": "055be730-dcad-31bf-b550-45ba9c202aa3",
        "title": "The Beatles",
        "year": 1968,
        "cover": "covers/beatles-beatles.jpg",
        "palette": [
          "#1a0f3a",
          "#e8a020",
          "#c0386b"
        ],
        "motif": "splash",
        "tracks": [
          [
            "Back in the U.S.S.R.",
            163
          ],
          [
            "Dear Prudence",
            236
          ],
          [
            "Glass Onion",
            138
          ],
          [
            "Ob‐La‐Di, Ob‐La‐Da",
            189
          ],
          [
            "Wild Honey Pie",
            53
          ],
          [
            "The Continuing Story of Bungalow Bill",
            194
          ],
          [
            "While My Guitar Gently Weeps",
            285
          ],
          [
            "Happiness Is a Warm Gun",
            163
          ],
          [
            "Martha My Dear",
            149
          ],
          [
            "I’m So Tired",
            123
          ],
          [
            "Blackbird",
            138
          ],
          [
            "Piggies",
            124
          ],
          [
            "Rocky Raccoon",
            213
          ],
          [
            "Don’t Pass Me By",
            230
          ],
          [
            "Why Don’t We Do It in the Road?",
            101
          ],
          [
            "I Will",
            106
          ],
          [
            "Julia",
            174
          ],
          [
            "Birthday",
            165
          ],
          [
            "Yer Blues",
            242
          ],
          [
            "Mother Nature’s Son",
            169
          ],
          [
            "Everybody’s Got Something to Hide Except Me and My Monkey",
            147
          ],
          [
            "Sexy Sadie",
            197
          ],
          [
            "Helter Skelter",
            271
          ],
          [
            "Long, Long, Long",
            185
          ],
          [
            "Revolution 1",
            256
          ],
          [
            "Honey Pie",
            162
          ],
          [
            "Savoy Truffle",
            176
          ],
          [
            "Cry Baby Cry",
            193
          ],
          [
            "Revolution 9",
            494
          ],
          [
            "Good Night",
            192
          ]
        ]
      },
      {
        "id": "beatles-abbey-road",
        "mbid": "9162580e-5df4-32de-80cc-f45a8d8a9b1d",
        "title": "Abbey Road",
        "year": 1969,
        "cover": "covers/beatles-abbey-road.jpg",
        "palette": [
          "#2d4a3e",
          "#e8e0c8",
          "#a8956b"
        ],
        "motif": "leaves",
        "tracks": [
          [
            "Come Together",
            261
          ],
          [
            "Something",
            183
          ],
          [
            "Maxwell’s Silver Hammer",
            207
          ],
          [
            "Oh! Darling",
            207
          ],
          [
            "Octopus’s Garden",
            171
          ],
          [
            "I Want You (She’s So Heavy)",
            467
          ],
          [
            "Here Comes the Sun",
            185
          ],
          [
            "Because",
            166
          ],
          [
            "You Never Give Me Your Money",
            242
          ],
          [
            "Sun King",
            147
          ],
          [
            "Mean Mr. Mustard",
            66
          ],
          [
            "Polythene Pam",
            73
          ],
          [
            "She Came in Through the Bathroom Window",
            117
          ],
          [
            "Golden Slumbers",
            92
          ],
          [
            "Carry That Weight",
            97
          ],
          [
            "The End",
            140
          ]
        ]
      },
      {
        "id": "beatles-let-it-be",
        "mbid": "bff544a7-56e0-3ed6-9e0f-3b676cca9111",
        "title": "Let It Be",
        "year": 1970,
        "cover": "covers/beatles-let-it-be.jpg",
        "palette": [
          "#5c3a1f",
          "#d4a574",
          "#8c5a2e"
        ],
        "motif": "soul",
        "tracks": [
          [
            "Two of Us",
            0
          ],
          [
            "I Me Mine",
            0
          ],
          [
            "One After 909",
            0
          ],
          [
            "Across the Universe",
            0
          ],
          [
            "Dig It",
            0
          ],
          [
            "Let It Be",
            0
          ],
          [
            "Maggie Mae",
            0
          ],
          [
            "Dig a Pony",
            0
          ],
          [
            "The Long & Winding Road",
            0
          ],
          [
            "I Got a Feeling",
            0
          ],
          [
            "For You Blue",
            0
          ],
          [
            "Get Back",
            0
          ]
        ]
      }
    ]
  }
};
